name: publish-docker-image
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up environment variables
        run: echo $GITHUB_ENV
      - name: Generate docker image labels and tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/jasonkolodziej/immich-ml-remote
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      #? Requires secret for actions: https://github.com/settings/tokens/new?scopes=write:packages,delete:packages
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            HW_ACCELERATOR=${{ env.HW_ACCELERATOR }}
